[project]
name = "coffee-lib"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "passlib>=1.7.4",
    "pydantic>=2.10.6",
    "requests>=2.32.3",
    "rich>=13.9.4",
]
